version: 2.1

jobs:
  build:
    working_directory: ~/usr/app
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: yarn test
